### ISSUE TITLE
Add shorthand property names (ES6)

### ISSUE THREAD

**Issue by Zorgatone** [aseemk/json5#107]
In ES6 (and similarly in HTML5 attributes)  you can use shorthand property names like this:

ES6:
```JavaScript
var a = "foo", 
    b = 42, 
    c = {};

// Shorthand property names (ES6)
var o = { a, b, c };
```

HTML5:
```HTML
<input type="checkbox" checked /> instead of <input type="checkbox" checked="checked" />
```

I think it would be useful to allow a similar behaviour in json5 (or you could even call it json6 for a future release, maybe?), in which the keys get the same value as a string

Example (json5/6):
```JavaScript
{
    checked, // converts to "checked":"checked"
    enabled
}
```

that would convert to (json):
```JSON
{
    "checked": "checked",
    "enabled": "enabled"
}
```

What do you think? I believe it can be a good shorthand in some cases.

**Comment by aseemk** [comment]
Thanks for the idea!

I'm reluctant with this feature, because `{checked}` is not the same as `{checked: "checked"}`.

A core principle of JSON5 is that it's a strict subset of (ES5) JavaScript. Even if we expanded that to ES6, this feature wouldn't pass that test: you couldn't e.g. paste that JSON5 snippet into an ES6 file without changing its meaning.
